apiVersion: harness.io/v1
kind: Component
type: backstage-node-library
identifier: backstage_backend_dev_utils
name: backstagebackend_dev_utils
owner: framework_maintainers
orgIdentifier: default
projectIdentifier: testrks
spec:
  lifecycle: experimental
