apiVersion: harness.io/v1
kind: Component
type: utility
identifier: test_repo_check
name: test_repo_check
owner: sandeepa@harness.io
orgIdentifier: default
projectIdentifier: testrks
spec:
  lifecycle: experimental
metadata:
  description: An example of a Backstage application.
